### Endpoint User Sign Up
POST http://localhost:5000/user
Content-Type: application/json

{
    "email": "",
    "password": ""
}

### Enpoint User Sign In
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "",
    "password": ""
}

### Password Reset Endpoints
POST http://localhost:5000/user/reset-password
Content-Type: application/json

{ 
    "email": ""
}

### Update New Password Endpoints
PATCH  http://localhost:5000/user/reset-password
Content-Type: application/json

{ 
    "email": "",
    "pin": "",
    "newPassword": ""
}